/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MylistRouteImport } from './routes/mylist'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as GenresRouteImport } from './routes/genres'
import { Route as CountryRouteImport } from './routes/country'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeriesIndexRouteImport } from './routes/series.index'
import { Route as MoviesIndexRouteImport } from './routes/movies.index'
import { Route as GenresIndexRouteImport } from './routes/genres.index'
import { Route as CountryIndexRouteImport } from './routes/country.index'
import { Route as SeriesSlugRouteImport } from './routes/series.$slug'
import { Route as MoviesSlugRouteImport } from './routes/movies.$slug'
import { Route as GenresIdRouteImport } from './routes/genres.$id'
import { Route as CountryIdRouteImport } from './routes/country.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MylistRoute = MylistRouteImport.update({
  id: '/mylist',
  path: '/mylist',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresRoute = GenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryRoute = CountryRouteImport.update({
  id: '/country',
  path: '/country',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesIndexRoute = SeriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SeriesRoute,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MoviesRoute,
} as any)
const GenresIndexRoute = GenresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GenresRoute,
} as any)
const CountryIndexRoute = CountryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CountryRoute,
} as any)
const SeriesSlugRoute = SeriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SeriesRoute,
} as any)
const MoviesSlugRoute = MoviesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MoviesRoute,
} as any)
const GenresIdRoute = GenresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GenresRoute,
} as any)
const CountryIdRoute = CountryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CountryRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/country': typeof CountryRouteWithChildren
  '/genres': typeof GenresRouteWithChildren
  '/movies': typeof MoviesRouteWithChildren
  '/mylist': typeof MylistRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/country/$id': typeof CountryIdRoute
  '/genres/$id': typeof GenresIdRoute
  '/movies/$slug': typeof MoviesSlugRoute
  '/series/$slug': typeof SeriesSlugRoute
  '/country/': typeof CountryIndexRoute
  '/genres/': typeof GenresIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/series/': typeof SeriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mylist': typeof MylistRoute
  '/search': typeof SearchRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/country/$id': typeof CountryIdRoute
  '/genres/$id': typeof GenresIdRoute
  '/movies/$slug': typeof MoviesSlugRoute
  '/series/$slug': typeof SeriesSlugRoute
  '/country': typeof CountryIndexRoute
  '/genres': typeof GenresIndexRoute
  '/movies': typeof MoviesIndexRoute
  '/series': typeof SeriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/country': typeof CountryRouteWithChildren
  '/genres': typeof GenresRouteWithChildren
  '/movies': typeof MoviesRouteWithChildren
  '/mylist': typeof MylistRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/country/$id': typeof CountryIdRoute
  '/genres/$id': typeof GenresIdRoute
  '/movies/$slug': typeof MoviesSlugRoute
  '/series/$slug': typeof SeriesSlugRoute
  '/country/': typeof CountryIndexRoute
  '/genres/': typeof GenresIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/series/': typeof SeriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/country'
    | '/genres'
    | '/movies'
    | '/mylist'
    | '/search'
    | '/series'
    | '/auth/callback'
    | '/country/$id'
    | '/genres/$id'
    | '/movies/$slug'
    | '/series/$slug'
    | '/country/'
    | '/genres/'
    | '/movies/'
    | '/series/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mylist'
    | '/search'
    | '/auth/callback'
    | '/country/$id'
    | '/genres/$id'
    | '/movies/$slug'
    | '/series/$slug'
    | '/country'
    | '/genres'
    | '/movies'
    | '/series'
  id:
    | '__root__'
    | '/'
    | '/country'
    | '/genres'
    | '/movies'
    | '/mylist'
    | '/search'
    | '/series'
    | '/auth/callback'
    | '/country/$id'
    | '/genres/$id'
    | '/movies/$slug'
    | '/series/$slug'
    | '/country/'
    | '/genres/'
    | '/movies/'
    | '/series/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountryRoute: typeof CountryRouteWithChildren
  GenresRoute: typeof GenresRouteWithChildren
  MoviesRoute: typeof MoviesRouteWithChildren
  MylistRoute: typeof MylistRoute
  SearchRoute: typeof SearchRoute
  SeriesRoute: typeof SeriesRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mylist': {
      id: '/mylist'
      path: '/mylist'
      fullPath: '/mylist'
      preLoaderRoute: typeof MylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres': {
      id: '/genres'
      path: '/genres'
      fullPath: '/genres'
      preLoaderRoute: typeof GenresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country': {
      id: '/country'
      path: '/country'
      fullPath: '/country'
      preLoaderRoute: typeof CountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/': {
      id: '/series/'
      path: '/'
      fullPath: '/series/'
      preLoaderRoute: typeof SeriesIndexRouteImport
      parentRoute: typeof SeriesRoute
    }
    '/movies/': {
      id: '/movies/'
      path: '/'
      fullPath: '/movies/'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof MoviesRoute
    }
    '/genres/': {
      id: '/genres/'
      path: '/'
      fullPath: '/genres/'
      preLoaderRoute: typeof GenresIndexRouteImport
      parentRoute: typeof GenresRoute
    }
    '/country/': {
      id: '/country/'
      path: '/'
      fullPath: '/country/'
      preLoaderRoute: typeof CountryIndexRouteImport
      parentRoute: typeof CountryRoute
    }
    '/series/$slug': {
      id: '/series/$slug'
      path: '/$slug'
      fullPath: '/series/$slug'
      preLoaderRoute: typeof SeriesSlugRouteImport
      parentRoute: typeof SeriesRoute
    }
    '/movies/$slug': {
      id: '/movies/$slug'
      path: '/$slug'
      fullPath: '/movies/$slug'
      preLoaderRoute: typeof MoviesSlugRouteImport
      parentRoute: typeof MoviesRoute
    }
    '/genres/$id': {
      id: '/genres/$id'
      path: '/$id'
      fullPath: '/genres/$id'
      preLoaderRoute: typeof GenresIdRouteImport
      parentRoute: typeof GenresRoute
    }
    '/country/$id': {
      id: '/country/$id'
      path: '/$id'
      fullPath: '/country/$id'
      preLoaderRoute: typeof CountryIdRouteImport
      parentRoute: typeof CountryRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CountryRouteChildren {
  CountryIdRoute: typeof CountryIdRoute
  CountryIndexRoute: typeof CountryIndexRoute
}

const CountryRouteChildren: CountryRouteChildren = {
  CountryIdRoute: CountryIdRoute,
  CountryIndexRoute: CountryIndexRoute,
}

const CountryRouteWithChildren =
  CountryRoute._addFileChildren(CountryRouteChildren)

interface GenresRouteChildren {
  GenresIdRoute: typeof GenresIdRoute
  GenresIndexRoute: typeof GenresIndexRoute
}

const GenresRouteChildren: GenresRouteChildren = {
  GenresIdRoute: GenresIdRoute,
  GenresIndexRoute: GenresIndexRoute,
}

const GenresRouteWithChildren =
  GenresRoute._addFileChildren(GenresRouteChildren)

interface MoviesRouteChildren {
  MoviesSlugRoute: typeof MoviesSlugRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
}

const MoviesRouteChildren: MoviesRouteChildren = {
  MoviesSlugRoute: MoviesSlugRoute,
  MoviesIndexRoute: MoviesIndexRoute,
}

const MoviesRouteWithChildren =
  MoviesRoute._addFileChildren(MoviesRouteChildren)

interface SeriesRouteChildren {
  SeriesSlugRoute: typeof SeriesSlugRoute
  SeriesIndexRoute: typeof SeriesIndexRoute
}

const SeriesRouteChildren: SeriesRouteChildren = {
  SeriesSlugRoute: SeriesSlugRoute,
  SeriesIndexRoute: SeriesIndexRoute,
}

const SeriesRouteWithChildren =
  SeriesRoute._addFileChildren(SeriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountryRoute: CountryRouteWithChildren,
  GenresRoute: GenresRouteWithChildren,
  MoviesRoute: MoviesRouteWithChildren,
  MylistRoute: MylistRoute,
  SearchRoute: SearchRoute,
  SeriesRoute: SeriesRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
